// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vendor_api.Data;

#nullable disable

namespace vendor_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("vendor_api.Models.Entities.Discipline", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisciplineId"));

                    b.Property<string>("DisciplineCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DisciplineName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("DisciplineId");

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            DisciplineId = 1,
                            DisciplineCode = "D01",
                            DisciplineName = "Control Software",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            DisciplineId = 2,
                            DisciplineCode = "D02",
                            DisciplineName = "Safety Software",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            DisciplineId = 3,
                            DisciplineCode = "D03",
                            DisciplineName = "Control Hardware",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            DisciplineId = 4,
                            DisciplineCode = "D04",
                            DisciplineName = "Safety Resource",
                            IsActive = true,
                            SortOrder = 4
                        },
                        new
                        {
                            DisciplineId = 5,
                            DisciplineCode = "D05",
                            DisciplineName = "RTU Resource",
                            IsActive = true,
                            SortOrder = 5
                        },
                        new
                        {
                            DisciplineId = 6,
                            DisciplineCode = "D06",
                            DisciplineName = "HMI Graphics",
                            IsActive = true,
                            SortOrder = 6
                        },
                        new
                        {
                            DisciplineId = 7,
                            DisciplineCode = "D07",
                            DisciplineName = "ACAD & MicroStation",
                            IsActive = true,
                            SortOrder = 7
                        },
                        new
                        {
                            DisciplineId = 8,
                            DisciplineCode = "D08",
                            DisciplineName = "CNV",
                            IsActive = true,
                            SortOrder = 8
                        },
                        new
                        {
                            DisciplineId = 9,
                            DisciplineCode = "D09",
                            DisciplineName = "TSI",
                            IsActive = true,
                            SortOrder = 9
                        },
                        new
                        {
                            DisciplineId = 10,
                            DisciplineCode = "D10",
                            DisciplineName = "F & G",
                            IsActive = true,
                            SortOrder = 10
                        },
                        new
                        {
                            DisciplineId = 11,
                            DisciplineCode = "D11",
                            DisciplineName = "TAS",
                            IsActive = true,
                            SortOrder = 11
                        },
                        new
                        {
                            DisciplineId = 12,
                            DisciplineCode = "D12",
                            DisciplineName = "FI",
                            IsActive = true,
                            SortOrder = 12
                        },
                        new
                        {
                            DisciplineId = 13,
                            DisciplineCode = "D13",
                            DisciplineName = "PHD",
                            IsActive = true,
                            SortOrder = 13
                        },
                        new
                        {
                            DisciplineId = 14,
                            DisciplineCode = "D14",
                            DisciplineName = "OTS",
                            IsActive = true,
                            SortOrder = 14
                        },
                        new
                        {
                            DisciplineId = 15,
                            DisciplineCode = "D15",
                            DisciplineName = "APM",
                            IsActive = true,
                            SortOrder = 15
                        },
                        new
                        {
                            DisciplineId = 16,
                            DisciplineCode = "D16",
                            DisciplineName = "HC900",
                            IsActive = true,
                            SortOrder = 16
                        },
                        new
                        {
                            DisciplineId = 17,
                            DisciplineCode = "D17",
                            DisciplineName = "Analytics",
                            IsActive = true,
                            SortOrder = 17
                        },
                        new
                        {
                            DisciplineId = 18,
                            DisciplineCode = "D18",
                            DisciplineName = "Experion HS / LX",
                            IsActive = true,
                            SortOrder = 18
                        },
                        new
                        {
                            DisciplineId = 19,
                            DisciplineCode = "D19",
                            DisciplineName = "Rockwell, Siemens, ABB, Schneider, Yokogawa",
                            IsActive = true,
                            SortOrder = 19
                        },
                        new
                        {
                            DisciplineId = 20,
                            DisciplineCode = "D20",
                            DisciplineName = "Skid",
                            IsActive = true,
                            SortOrder = 20
                        },
                        new
                        {
                            DisciplineId = 21,
                            DisciplineCode = "D21",
                            DisciplineName = "ES-RPMO",
                            IsActive = true,
                            SortOrder = 21
                        },
                        new
                        {
                            DisciplineId = 22,
                            DisciplineCode = "D22",
                            DisciplineName = "e-Learning",
                            IsActive = true,
                            SortOrder = 22
                        },
                        new
                        {
                            DisciplineId = 23,
                            DisciplineCode = "D23",
                            DisciplineName = "Misc. LSS",
                            IsActive = true,
                            SortOrder = 23
                        },
                        new
                        {
                            DisciplineId = 24,
                            DisciplineCode = "D24",
                            DisciplineName = "Misc. HCP",
                            IsActive = true,
                            SortOrder = 24
                        },
                        new
                        {
                            DisciplineId = 25,
                            DisciplineCode = "D25",
                            DisciplineName = "TFMS",
                            IsActive = true,
                            SortOrder = 25
                        },
                        new
                        {
                            DisciplineId = 26,
                            DisciplineCode = "D26",
                            DisciplineName = "Other",
                            IsActive = true,
                            SortOrder = 26
                        });
                });

            modelBuilder.Entity("vendor_api.Models.Entities.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            GroupCode = "SE",
                            GroupName = "SE",
                            IsActive = true
                        },
                        new
                        {
                            GroupId = 2,
                            GroupCode = "ES",
                            GroupName = "ES",
                            IsActive = true
                        },
                        new
                        {
                            GroupId = 3,
                            GroupCode = "LSS",
                            GroupName = "LSS",
                            IsActive = true
                        },
                        new
                        {
                            GroupId = 4,
                            GroupCode = "AS",
                            GroupName = "AS",
                            IsActive = true
                        },
                        new
                        {
                            GroupId = 5,
                            GroupCode = "DFE",
                            GroupName = "DFE",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("vendor_api.Models.Entities.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourceId"));

                    b.Property<DateTime?>("AvailableFromDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CurrentProjectName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("DisciplineId")
                        .HasColumnType("int");

                    b.Property<string>("EngineerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ManagerName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("RelevantExperienceYears")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SkillLevelId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalExperienceYears")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("ResourceId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("GroupId");

                    b.HasIndex("SkillLevelId");

                    b.HasIndex("VendorId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("vendor_api.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "vendor"
                        },
                        new
                        {
                            Id = 2,
                            Name = "admin"
                        });
                });

            modelBuilder.Entity("vendor_api.Models.Entities.SkillLevel", b =>
                {
                    b.Property<int>("SkillLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillLevelId"));

                    b.Property<int>("RankOrder")
                        .HasColumnType("int");

                    b.Property<string>("SkillCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SkillLevelId");

                    b.ToTable("SkillLevels");

                    b.HasData(
                        new
                        {
                            SkillLevelId = 1,
                            RankOrder = 0,
                            SkillCode = "L0",
                            SkillName = "Can Not Do"
                        },
                        new
                        {
                            SkillLevelId = 2,
                            RankOrder = 1,
                            SkillCode = "L1",
                            SkillName = "Can Do Under Supervision"
                        },
                        new
                        {
                            SkillLevelId = 3,
                            RankOrder = 2,
                            SkillCode = "L2",
                            SkillName = "Can Do Independently"
                        },
                        new
                        {
                            SkillLevelId = 4,
                            RankOrder = 3,
                            SkillCode = "L3",
                            SkillName = "Can Supervise Others"
                        },
                        new
                        {
                            SkillLevelId = 5,
                            RankOrder = 4,
                            SkillCode = "L4",
                            SkillName = "Subject Matter Expert"
                        });
                });

            modelBuilder.Entity("vendor_api.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("VendorId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ram@company.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$OqRafa/PkksFMZrL0pmErebHmtZWsg.dehA3cSdO.wW.JkS8QQPEe",
                            RoleId = 1,
                            Username = "ram",
                            VendorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "shiva@company.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$Za7uzwmM3aONCBJTobuoeO8LXJBdl8ECvaH3sPGWdB1Zqk9QcGhz2",
                            RoleId = 2,
                            Username = "shiva"
                        });
                });

            modelBuilder.Entity("vendor_api.Models.Entities.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendorId"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VendorId");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            VendorId = 1,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            VendorName = "Honeywell"
                        },
                        new
                        {
                            VendorId = 2,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            VendorName = "Esskay"
                        },
                        new
                        {
                            VendorId = 3,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            VendorName = "Emerson"
                        },
                        new
                        {
                            VendorId = 4,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            VendorName = "ABB"
                        },
                        new
                        {
                            VendorId = 5,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            VendorName = "Rockwell"
                        },
                        new
                        {
                            VendorId = 6,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            VendorName = "Schneider"
                        },
                        new
                        {
                            VendorId = 7,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            VendorName = "Yokogawa"
                        });
                });

            modelBuilder.Entity("vendor_api.Models.Entities.Resource", b =>
                {
                    b.HasOne("vendor_api.Models.Entities.Discipline", "Discipline")
                        .WithMany("Resources")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("vendor_api.Models.Entities.Group", "Group")
                        .WithMany("Resources")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("vendor_api.Models.Entities.SkillLevel", "SkillLevel")
                        .WithMany("Resources")
                        .HasForeignKey("SkillLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("vendor_api.Models.Entities.Vendor", "Vendor")
                        .WithMany("Resources")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Group");

                    b.Navigation("SkillLevel");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("vendor_api.Models.Entities.User", b =>
                {
                    b.HasOne("vendor_api.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("vendor_api.Models.Entities.Vendor", "Vendor")
                        .WithMany("Users")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("vendor_api.Models.Entities.Discipline", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("vendor_api.Models.Entities.Group", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("vendor_api.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("vendor_api.Models.Entities.SkillLevel", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("vendor_api.Models.Entities.Vendor", b =>
                {
                    b.Navigation("Resources");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
